config/routes.rb
Bobop::Application.routes.draw do
  
  resources :images

  resources :posts

  devise_for :users

  resources :projects

  resources :clients

  match 'services' => "pages#services", :as => :services

  match 'contact' => "pages#contact", :as => :contact
  
  root :to => 'pages#home'

  match '/sitemap' => 'sitemap#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :projects
  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x50>" },
       :storage => :s3,
       :s3_credentials => S3_CREDENTIALS,
       :path => "clients/:style/:id/:filename"
  
  def to_param
    "#{slug}"
  end

  def slug
  	"#{id}-#{name.gsub(/[^a-z0-9]+/i, '-')}"
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :ok }
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.haml
= form_for @client do |f|
  -if @client.errors.any?
    #error_explanation
      %h2= "#{pluralize(@client.errors.count, "error")} prohibited this client from being saved:"
      %ul
        - @client.errors.full_messages.each do |msg|
          %li= msg

  .field.clearfix
    = f.label :name
    .input= f.text_field :name
  .field.clearfix
    = f.label :website
    .input= f.text_field :website
  .field.clearfix
    = f.label :logo
    .input= f.file_field :logo
  .field.clearfix
    = f.label :description
    .input= f.text_area :description, :class => "span12"
  .actions
    = f.submit 'Save'

app/views/clients/edit.html.haml
%h1 Editing client

= render 'form'

= link_to 'Show', @client
\|
= link_to 'Back', clients_path

app/views/clients/index.html.haml
- content_for :head do
  %title Clients - Bobop - Freelance Ruby on Rails developer based in Manchester

.row
  .span12.content
    %h1 Clients
    %p My clients have ranged from VC funded music industry startups to Insurance Premium Tax companies. Unfortunately I'm not able to list some of these clients because I worked for them through other agencies. Do contact me if you want to know about them.
    %p Here are some of my latest clients:
    %p= link_to 'New Client', new_client_path if current_user
    - @clients.each do |client|
      .row
        .span12.content
          .f_right
            = image_tag client.logo.url(:medium)
          %h2= client.name
          %h3= link_to client.website, client.website
          %p= link_to "More Details »", client_path(client), :class => "btn"
          %p= link_to 'Edit', edit_client_path(client) if current_user
          %p= link_to 'Destroy', client, :confirm => 'Are you sure?', :method => :delete if current_user

app/views/clients/new.html.haml
%h1 New client

= render 'form'

= link_to 'Back', clients_path

app/views/clients/show.html.haml
- content_for :head do
  %title
    = "#{@client.name} -"
    Bobop - Freelance Ruby on Rails developer based in Manchester

.row
  .span12.content
    .row
      .span8
        
        %h1= @client.name
        %h2= link_to @client.website, @client.website
        %p=raw @client.description
      .span4
        .show_logo
          = image_tag @client.logo.url(:medium)
        .list_box
          .list_content
            %h2 Projects
            - @client.projects.each do |p|
              .logo
                = link_to image_tag(p.logo.url(:thumb)), project_path(p)
              %h3= link_to p.name, project_path(p)