config/routes.rb
Bobop::Application.routes.draw do
  
  resources :images

  resources :posts

  devise_for :users

  resources :projects

  resources :clients

  match 'services' => "pages#services", :as => :services

  match 'contact' => "pages#contact", :as => :contact
  
  root :to => 'pages#home'

  match '/sitemap' => 'sitemap#index'

end

app/views/pages/contact.html.haml
- content_for :head do
  %title Contact Bobop - Freelance Ruby on Rails developer based in Manchester

.row
  .span12.content
    .row
      .span8
        %h1 Contact Me
        %p I am available to hire so contact me through the details below to discuss your project:
        .row{:itemscope => "", :itemtype =>"http://schema.org/Person"}
          .span4
            %p{:itemprop => "telephone"} 07811197374
            %p{:itemprop => "email"}= link_to "ben@bobop.co.uk", "mailto:ben@bobop.co.uk"
            %address{:itemprop => "address", :itemscope => "", :itemtype =>"http://schema.org/PostalAddress"}
              %strong{:itemprop => "name"} Ben Gibbs
              %br
              %span{:itemprop => "streetAddress"}
                120/122 Grosvenor St
              %br
              %span{:itemprop => "addressLocality"}Manchester
              %br
              %span{:itemprop => "postalCode"}M1 7HL
          .span4
            %p= link_to "Twitter", "http://twitter.com/bobop", :rel => "me"
            %p= link_to "Github", "http://github.com/bobop", :rel => "me"
            %p= link_to "LinkedIn", "http://uk.linkedin.com/in/benjgibbs", :rel => "me"
            %p= link_to "Facebook", "http://facebook.com/boboppage", :rel => "me"
            %p= link_to "Google+", "https://plus.google.com/111410012808185125992/posts", :rel => "me author"
            %p= link_to "Working With Rails", "http://workingwithrails.com/person/17173-ben-gibbs", :rel => "me"
      .span4.list_box
        .list_content
          %h3 Twitter Feed
          #tweets
          = link_to "Follow @bobop", "https://twitter.com/bobop", :class => "twitter-follow-button"
          %script{:type => "text/javascript", :src => "//platform.twitter.com/widgets.js"}
 

app/views/pages/home.html.haml
- content_for :head do
  %title Bobop - Freelance Ruby on Rails developer based in Manchester
  %meta{:name => 'description', :content => "I'm a Freelance Ruby on Rails developer based in Manchester and am available for Hire. I use Agile, Behaviour Driven Development (BDD), Git, HTML5, CSS3, jQuery, MySQL, Postgresql, Heroku, Brightbox"}
.row{:itemscope => "", :itemtype =>"http://schema.org/Person"}
  .span12.highlight
    .row
      .span8.offset1
        .list_content
          %h1 
            Hello, I'm 
            %span{:itemprop => "name"}Ben Gibbs
          %h2 
            I am a 
            %span{:itemprop => "jobTitle"} Freelance Ruby on Rails developer 
            based in Manchester
          = link_to "Available for hire", contact_path, :class => "btn btn-danger btn-large" 
      .span1.offset1
        .social
          = link_to image_tag("twitter.png"), "http://twitter.com/bobop", "data-placement" => "right", :rel => 'twipsy me', :title => 'Bobop on Twitter', :class => "twipsy_popover"
        .social
          = link_to image_tag("github.png"), "http://github.com/bobop", "data-placement" => "right", :rel => 'twipsy me', :title => 'Bobop on Github', :class => "twipsy_popover"
        .social
          = link_to image_tag("linkedin.png"), "http://uk.linkedin.com/in/benjgibbs", "data-placement" => "right", :rel => 'twipsy me', :title => 'Bobop on LinkedIn', :class => "twipsy_popover"
        .social
          = link_to image_tag("facebook.png"), "http://facebook.com/boboppage", "data-placement" => "right", :rel => 'twipsy me', :title => 'Bobop on Facebook', :class => "twipsy_popover"
        .social
          = link_to image_tag("googleplus.png"), "https://plus.google.com/111410012808185125992/posts", "data-placement" => "right", :rel => 'twipsy me author', :title => 'Bobop on Google+', :class => "twipsy_popover"
        .social{:itemprop => "email"}
          = link_to image_tag("email.png"), "mailto:ben@bobop.co.uk", "data-placement" => "right", :rel => 'twipsy me', :title => 'Email Bobop', :class => "twipsy_popover"
.row
  .span8
    .row
      .span8.list_box
        .list_content
          %h3 About Me
          %p 
            I have built a variety of live websites and web apps using Ruby and Rails over the last 5 years. I develop using an Agile process, Behaviour Driven Development and Git. Much of my work is deployed to either
            = link_to "Heroku", "http://heroku.com"
            or
            = link_to "Brightbox.", "http://brightbox.co.uk"
          %p 
            I'm an active member of a number of local groups. I regularly attend
            = link_to "North West Ruby User Group", "http://nwrug.org"
            and co-started 
            = link_to "Manchester's BootStrap Business Club", "http://bootstrapbusinessclub.co.uk"
            , a social gathering of people to discuss building sustainable businesses and projects. I run 
            = link_to "Manchester Jelly,", "http://manchesterjelly.wordpress.com"
            Manchester's free, casual co-working event, I am a member of 
            = link_to "Open Data Manchester", "http://opendatamanchester.org.uk"
            and am the developer representative on the 
            = link_to "DataGM", "http://datagm.org.uk"
            Steering Committee.
    .row
      .span4.list_box
        .list_content
          %h3 Blog
          - @posts.each do |p|
            .item
              %h4 
                = link_to p.title, post_path(p)
              .small= p.date
          %p= link_to "See more Blog posts »", posts_path, :class => "btn"
      .span4.list_box
        .list_content
          %h3 Latest Projects
          - @projects.each do |p|
            .item
              .logo
                = link_to image_tag(p.logo.url(:thumb)), project_path(p) if p.logo.present?
              %h4 
                = link_to p.name, project_path(p)
              .small= p.client ? "for #{p.client.name}" : "a Bobop original"
          %p
            = link_to "See all my Projects »", projects_path, :class => "btn"
            = link_to "See my Clients »", clients_path, :class => "btn"
  .span4.list_box
    .list_content
      %h3 Twitter Feed
      #tweets
      = link_to "Follow @bobop", "https://twitter.com/bobop", :class => "twitter-follow-button"
      %script{:type => "text/javascript", :src => "//platform.twitter.com/widgets.js"}

app/views/pages/services.html.haml
- content_for :head do
  %title Bobop Services - Freelance Ruby on Rails developer based in Manchester

.row
  .span12.content
    .row
      .span8
        %h1 Ruby On Rails Services
        %h2 Agile
        %p Developing web apps in short cycles, usually 2 weeks, means that new ideas, issues or direction can be quickly adopted during development.
        %pIt avoids finalising a specification for the site, then having that delivered a couple of months later and finding that in the meantime:
        %ul
          %li your business model has been tweaked,
          %li you’ve received feedback suggesting different features are needed,
          %li you’ve realised that some features are not necessary,
          %li you’ve had new ideas for the User Interface,
          %li etc… but it’s too late.
        %p Using Agile helps refine your product to function and look the way it needs to as your business evolves.
        %h2 Lean
        %p I encourage my clients to adopt Lean practices when starting a new web app. Start with the minimum viable product, then build on that according to the feedback from your users. Or you could waste time and money on features which you think are wonderful, but your user’s aren’t interested in!
        %h2 Behaviour Driven Development (BDD)
        %p BDD creates tests which describe how the web app should respond according to user’s actions. The tests are written so that a non-techy person can understand what the app is supposed to do, and a computer can run the tests to see if they pass or fail. Of course, they should all pass or the app is unstable!
      .span4.list_box
        .list_content
          %h3 Twitter Feed
          #tweets
          = link_to "Follow @bobop", "https://twitter.com/bobop", :class => "twitter-follow-button"
          %script{:type => "text/javascript", :src => "//platform.twitter.com/widgets.js"}