config/routes.rb
Bobop::Application.routes.draw do
  
  resources :images

  resources :posts

  devise_for :users

  resources :projects

  resources :clients

  match 'services' => "pages#services", :as => :services

  match 'contact' => "pages#contact", :as => :contact
  
  root :to => 'pages#home'

  match '/sitemap' => 'sitemap#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :client
  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x50>" },
       :storage => :s3,
       :s3_credentials => S3_CREDENTIALS,
       :path => "projects/:style/:id/:filename"
  has_attached_file :screenshot, :styles => { :medium => "580x580>", :thumb => "100x100>" },
      :storage => :s3,
      :s3_credentials => S3_CREDENTIALS,
      :path => "screenshots/:style/:id/:filename"

  def to_param
    "#{slug}"
  end

  def slug
    "#{id}-#{name.gsub(/[^a-z0-9]+/i, '-')}"
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.order("completed_at DESC").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  -if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field.clearfix
    = f.label :client_id
    .input= f.select :client_id, Client.all.collect {|p| [ p.name, p.id ] }, { :include_blank => true }
  .field.clearfix
    = f.label :name
    .input= f.text_field :name
  .field.clearfix
    = f.label :website
    .input= f.text_field :website
  .field.clearfix
    = f.label :logo
    .input= f.file_field :logo
  .field.clearfix
    = f.label :screenshot
    .input= f.file_field :screenshot
  .field.clearfix
    = f.label :description
    .input= f.text_area :description, :class => "span12"
  .field.clearfix
    = f.label :completed_at
    .input= f.date_select :completed_at
  .actions
    = f.submit 'Save'

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
- content_for :head do
  %title Projects - Bobop - Freelance Ruby on Rails developer based in Manchester

.row
  .span12.content
    %h1 Projects
    %p I have worked on many varied Ruby on Rails projects over the last 5 years.
    %p Here are some of my latest projects:
    %p= link_to 'New Project', new_project_path if current_user
    - @projects.each do |project|
      .row
        .span12.content
          .f_right
            = image_tag project.logo.url(:medium)
          %h2
            = project.name
            %small= project.client ? "for #{project.client.name}" : "a Bobop original"
            
          %h3= link_to project.website, project.website
          %p= link_to "More Details »", project_path(project), :class => "btn"
          %p= link_to 'Edit', edit_project_path(project) if current_user
          %p= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete if current_user

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
- content_for :head do
  %title
    = "#{@project.name} -"
    Bobop - Freelance Ruby on Rails developer based in Manchester

.row
  .span12.content
    .row
      .span9
        
        
        %h1
          = @project.name
          %small= @project.client ? "for #{@project.client.name}" : "a Bobop original"
          
        %h2= link_to @project.website, @project.website
        = image_tag @project.screenshot.url(:medium), :class => "screenshot"
        %p=raw @project.description
      .span3.show_logo
        = image_tag @project.logo.url(:medium)