config/routes.rb
Bobop::Application.routes.draw do
  
  resources :images

  resources :posts

  devise_for :users

  resources :projects

  resources :clients

  match 'services' => "pages#services", :as => :services

  match 'contact' => "pages#contact", :as => :contact
  
  root :to => 'pages#home'

  match '/sitemap' => 'sitemap#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
                
  def to_param
    "#{slug}"
  end

  def slug
  	"#{id}-#{title.gsub(/[^a-z0-9]+/i, '-')}"
  end
  
  def date
    created_at.strftime("%d %b %y")
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("created_at DESC").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.xml { render :layout => false }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @image = Image.new
    @images = Image.order("created_at DESC").all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    @images = Image.order("created_at DESC").all
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for @post do |f|
  -if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field.clearfix
    = f.label :title
    .input= f.text_field :title
  .field.clearfix
    = f.label :content
    .input= f.text_area :content, :class => "span12"
  .field.clearfix
    = label_tag "Images"
    .input
      = link_to "Upload Image", new_image_path, :class => "btn", :target => "_blank"
      .image_container
        #images
          = render 'images/latest_images'
  .field.clearfix
    = f.label :publish
    .input= f.check_box :publish
  .field.clearfix
    = f.label :created_at
    .input= f.date_select :created_at
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
- content_for :head do
  %title Blog - Bobop - Freelance Ruby on Rails developer based in Manchester

.row
  .span12.content
    %h1 Blog
    %p= link_to 'New Post', new_post_path if current_user
    - @posts.each do |post|
      .row
        .span12.content
          %h2
            = post.title
            %small= post.date
          %p= "#{strip_tags(post.content)[0..300]}..."
          %p= link_to "Read More »", post_path(post), :class => "btn"
          %p= link_to 'Edit', edit_post_path(post) if current_user
          %p= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete if current_user

app/views/posts/index.rss.haml
- base_url = "http://#{request.host_with_port}"
!!! XML
%rss{ :version => "2.0" }
  %channel
    %title Bobop - Freelance Ruby on Rails developer based in Manchester
    %link= base_url
    %description The blog of Bobop
    - @posts.each do |p|
      %item
        %title= p.title
        %description=raw p.content
        %link #{base_url}/posts/#{p.slug}
        %pubDate= p.created_at
        %author ben@bobop.co.uk

app/views/posts/index.xml.haml
- base_url = "http://#{request.host_with_port}"
!!! XML
<?xml version="1.0"?>
%rss{ :version => "2.0" }
  %channel
    %title Bobop - Freelance Ruby on Rails developer based in Manchester
    %link= base_url
    %description The blog of Bobop
    - @posts.each do |p|
      %item
        %title= p.title
        %description= HTMLEntities.new.decode(p.content)
        %link #{base_url}/posts/#{p.slug}
        %pubDate= p.created_at
        %author ben@bobop.co.uk

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
- content_for :head do
  %title
    = "#{@post.title} -"
    Bobop - Freelance Ruby on Rails developer based in Manchester

.row
  .span12.content
    .row
      .span8.post
        %h1
          = @post.title
          %small= @post.date
        =raw @post.content
      .span4.list_box
        .list_content
          %h3 Twitter Feed
          #tweets
          = link_to "Follow @bobop", "https://twitter.com/bobop", :class => "twitter-follow-button"
          %script{:type => "text/javascript", :src => "//platform.twitter.com/widgets.js"}